language: c

os:
  - osx
  - linux

compiler:
    - clang
    - gcc

env:
  matrix:
    - TOX_ENV=lint
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=pypy
    - TOX_ENV=docs
    - TOX_ENV=docs-spellcheck
    - TOX_ENV=docs-linkcheck
    - TOX_ENV=bundle

matrix:
  allow_failures:
    - env: TOX_ENV=docs-linkcheck
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

    # no need to build docs on OSX
    - os: osx
      env: TOX_ENV=docs
    - os: osx
      env: TOX_ENV=docs-spellcheck
    - os: osx
      env: TOX_ENV=docs-linkcheck

    # don't build mac app on linux
    - os: linux
      env: TOX_ENV=bundle

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh

after_success:
    - source ~/.venv/bin/activate && coveralls

# notifications:
#   irc:
#     channels: "chat.freenode.net##mimic"
#     template:
#       - "%{repository}@%{branch} - %{author}: %{message} (%{build_url})"
#     use_notice: true
