language: python
os:
  - osx
  - linux

env:
  - TOX_ENV=lint
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=pypy
  - TOX_ENV=docs
  - TOX_ENV=docs-spellcheck
  - TOX_ENV=docs-linkcheck
  - TOX_ENV=bundle

matrix:
  allow_failures:
    - env: "TOX_ENV=docs-linkcheck"

  exclude:
    - os: osx
      env: lint
    - os: osx
      env: py26
    - os: osx
      env: py27
    - os: osx
      env: docs
    - os: osx
      env: docs-spellcheck
    - os: osx
      env: docs-linkcheck
    - os: linux
      env: bundle

install:
  - ./.travis/install.sh

script: tox -e $TOX_ENV

after_success:
    - if [[ "${TOX_ENV:0:2}" == 'py' ]]; then coveralls; fi

notifications:
  irc:
    channels: "chat.freenode.net##mimic"
    template:
      - "%{repository}@%{branch} - %{author}: %{message} (%{build_url})"
    use_notice: true
